//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseContext
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class UserTbl
    {
        [NotMapped]
        public HttpPostedFileBase File { get; set; }
        [NotMapped]
        public HttpPostedFileBase CollegePhotoFile { get; set; }
         [NotMapped]
        public HttpPostedFileBase CouplePhotoFile { get; set; }
        [NotMapped]
        public HttpPostedFileBase FamilyPhotoFile { get; set; }

        public int UserID { get; set; }
        public int UserTypeID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string AdditionalName { get; set; }
        public Nullable<long> MobileNo { get; set; }
        public Nullable<long> AlternateMobileNo { get; set; }
        public Nullable<long> LandlineNo { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
        public string Gender { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string MaritalStatus { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> MarriageDate { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Description { get; set; }
        public string Profession { get; set; }
        public string Hobbies { get; set; }
        public string Experience { get; set; }
        public string FamilyInfo { get; set; }
        public string OtherInfo { get; set; }
        public string Photo { get; set; }
        public string CollegePhoto { get; set; }
        public string CouplePhoto { get; set; }
        public string FamilyPhoto { get; set; }
    
        public virtual UserTypeTbl UserTypeTbl { get; set; }
    }
}
